repos:
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: master
  - hooks:
      - additional_dependencies:
          - "@commitlint/config-conventional"
        id: commitlint
        stages:
          - commit-msg
    repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
