[tools]
deno = "latest"
elixir = "latest"
flutter = "latest"
golang = "latest"
node = "latest"
python = "latest"
rust = "latest"
yarn = "latest"
go = "latest"
pnpm = "latest"
dotnet-core = "latest"
erlang = "latest"
