[directory]
truncation_length = 100
truncate_to_repo = false

[memory_usage]
disabled = false

[status]
disabled = false

[sudo]
disabled = false

[username]
show_always = true

[time]
disabled = false
time_format = "%F|%T"

[git_metrics]
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"
